// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/event/event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/event/event.go -destination=./internal/pkg/event/mock/event_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	models "go-flip-life-style-products/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEvent) Publish(evt models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventMockRecorder) Publish(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEvent)(nil).Publish), evt)
}

// Subscribe mocks base method.
func (m *MockEvent) Subscribe() <-chan models.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan models.Event)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEvent)(nil).Subscribe))
}
