// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/file/file.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/file/file.go -destination=./internal/pkg/file/mock/file_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFile is a mock of File interface.
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *MockFileMockRecorder
}

// MockFileMockRecorder is the mock recorder for MockFile.
type MockFileMockRecorder struct {
	mock *MockFile
}

// NewMockFile creates a new mock instance.
func NewMockFile(ctrl *gomock.Controller) *MockFile {
	mock := &MockFile{ctrl: ctrl}
	mock.recorder = &MockFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFile) EXPECT() *MockFileMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockFile) Save(file *multipart.FileHeader, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", file, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFileMockRecorder) Save(file, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFile)(nil).Save), file, dst)
}
