// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/balance.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/balance.go -destination=./internal/services/mock/balance_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "go-flip-life-style-products/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalance is a mock of Balance interface.
type MockBalance struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceMockRecorder
}

// MockBalanceMockRecorder is the mock recorder for MockBalance.
type MockBalanceMockRecorder struct {
	mock *MockBalance
}

// NewMockBalance creates a new mock instance.
func NewMockBalance(ctrl *gomock.Controller) *MockBalance {
	mock := &MockBalance{ctrl: ctrl}
	mock.recorder = &MockBalanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalance) EXPECT() *MockBalanceMockRecorder {
	return m.recorder
}

// GetBalanceByUploadID mocks base method.
func (m *MockBalance) GetBalanceByUploadID(ctx context.Context, uploadID string) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUploadID", ctx, uploadID)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUploadID indicates an expected call of GetBalanceByUploadID.
func (mr *MockBalanceMockRecorder) GetBalanceByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUploadID", reflect.TypeOf((*MockBalance)(nil).GetBalanceByUploadID), ctx, uploadID)
}
