// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/statements.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/statements.go -destination=./internal/services/mock/statements_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatements is a mock of Statements interface.
type MockStatements struct {
	ctrl     *gomock.Controller
	recorder *MockStatementsMockRecorder
}

// MockStatementsMockRecorder is the mock recorder for MockStatements.
type MockStatementsMockRecorder struct {
	mock *MockStatements
}

// NewMockStatements creates a new mock instance.
func NewMockStatements(ctrl *gomock.Controller) *MockStatements {
	mock := &MockStatements{ctrl: ctrl}
	mock.recorder = &MockStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatements) EXPECT() *MockStatementsMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockStatements) Upload(ctx context.Context, file *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockStatementsMockRecorder) Upload(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStatements)(nil).Upload), ctx, file)
}
