// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/transaction.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/transaction.go -destination=./internal/services/mock/transaction_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "go-flip-life-style-products/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// GetListIssuesTransaction mocks base method.
func (m *MockTransaction) GetListIssuesTransaction(ctx context.Context, req models.ReqGetListIssuesTransaction) ([]models.Transaction, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListIssuesTransaction", ctx, req)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetListIssuesTransaction indicates an expected call of GetListIssuesTransaction.
func (mr *MockTransactionMockRecorder) GetListIssuesTransaction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListIssuesTransaction", reflect.TypeOf((*MockTransaction)(nil).GetListIssuesTransaction), ctx, req)
}

// Store mocks base method.
func (m *MockTransaction) Store(ctx context.Context, tx models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTransactionMockRecorder) Store(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTransaction)(nil).Store), ctx, tx)
}
