// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/queue/queue.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/queue/queue.go -destination=./internal/pkg/queue/mock/queue_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	models "go-flip-life-style-products/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockQueue) Channel() <-chan models.UploadQueue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(<-chan models.UploadQueue)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockQueueMockRecorder) Channel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockQueue)(nil).Channel))
}

// Enqueue mocks base method.
func (m *MockQueue) Enqueue(job models.UploadQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueMockRecorder) Enqueue(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueue)(nil).Enqueue), job)
}
