// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/transaction.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/transaction.go -destination=./internal/repositories/mock/transaction_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "go-flip-life-style-products/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTransaction) Add(tx models.Transaction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", tx)
}

// Add indicates an expected call of Add.
func (mr *MockTransactionMockRecorder) Add(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTransaction)(nil).Add), tx)
}

// ListTransactionByUploadID mocks base method.
func (m *MockTransaction) ListTransactionByUploadID(ctx context.Context, uploadID string, filter *models.FilterTransaction) ([]models.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionByUploadID", ctx, uploadID, filter)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactionByUploadID indicates an expected call of ListTransactionByUploadID.
func (mr *MockTransactionMockRecorder) ListTransactionByUploadID(ctx, uploadID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionByUploadID", reflect.TypeOf((*MockTransaction)(nil).ListTransactionByUploadID), ctx, uploadID, filter)
}
